# Generated by Django 4.2.1 on 2023-06-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('deptid', models.IntegerField()),
            ],
        ),
    ]
